### ISSUE TITLE
Yii2-usuario supported?

### ISSUE THREAD

**Issue by WeeSee** [niciz/yii2-message#1]
Yii2-user is an abandoned projekt for a longe time (>5 years).

Does this projekt support [Yii2-usuario](https://github.com/2amigos/yii2-usuario)?

**Comment by niciz** [comment]
Hi @WeeSee 
This is a fork of https://gitlab.com/thyseus/yii2-message with one bugfix commit.
I personally use this with yii2-usuario without problems.
If you have any issue with usuario we can check it and solve.
